import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repositoryRoot = path.resolve(packageRoot, "..");
const registryPath = path.join(packageRoot, "tokens", "design-system.tokens.json");

const stripComments = (value) => value.replace(/\/\*[\s\S]*?\*\//g, "");

function matchingBrace(source, openIndex) {
  let depth = 0;
  let quote = null;
  let comment = false;

  for (let index = openIndex; index < source.length; index += 1) {
    const char = source[index];
    const next = source[index + 1];

    if (comment) {
      if (char === "*" && next === "/") {
        comment = false;
        index += 1;
      }
      continue;
    }
    if (!quote && char === "/" && next === "*") {
      comment = true;
      index += 1;
      continue;
    }
    if (quote) {
      if (char === "\\") index += 1;
      else if (char === quote) quote = null;
      continue;
    }
    if (char === '"' || char === "'") {
      quote = char;
      continue;
    }
    if (char === "{") depth += 1;
    if (char === "}") {
      depth -= 1;
      if (depth === 0) return index;
    }
  }

  throw new Error("Bloco CSS sem fechamento.");
}

function splitDeclarations(body) {
  const declarations = [];
  let start = 0;
  let quote = null;
  let parentheses = 0;

  for (let index = 0; index <= body.length; index += 1) {
    const char = body[index];
    if (quote) {
      if (char === "\\") index += 1;
      else if (char === quote) quote = null;
      continue;
    }
    if (char === '"' || char === "'") {
      quote = char;
      continue;
    }
    if (char === "(") parentheses += 1;
    if (char === ")") parentheses -= 1;
    if ((char === ";" || index === body.length) && parentheses === 0) {
      const declaration = body.slice(start, index).trim();
      const separator = declaration.indexOf(":");
      if (separator > 0) {
        declarations.push({
          property: declaration.slice(0, separator).trim(),
          value: declaration.slice(separator + 1).trim(),
        });
      }
      start = index + 1;
    }
  }

  return declarations;
}

function parseRules(source, { layer = false } = {}) {
  let content = stripComments(source).trim();
  if (layer) {
    const layerStart = content.indexOf("{");
    if (layerStart < 0) throw new Error("@layer base sem bloco.");
    const layerEnd = matchingBrace(content, layerStart);
    content = content.slice(layerStart + 1, layerEnd);
  }

  const rules = [];
  let cursor = 0;
  while (cursor < content.length) {
    const open = content.indexOf("{", cursor);
    if (open < 0) break;
    const selector = content.slice(cursor, open).trim();
    const close = matchingBrace(content, open);
    const declarations = splitDeclarations(content.slice(open + 1, close));
    if (selector && declarations.length > 0) rules.push({ selector, declarations });
    cursor = close + 1;
  }
  return rules;
}

function createRegistry() {
  const tokensPath = path.join(packageRoot, "src", "tokens.css");
  const themesPath = path.join(packageRoot, "src", "themes.css");
  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    version: 1,
    description: "Fonte unica dos tokens e presets de tema da VERSI Design System.",
    tokens: parseRules(fs.readFileSync(tokensPath, "utf8"), { layer: true }),
    themes: parseRules(fs.readFileSync(themesPath, "utf8")),
  };
}

function renderRules(rules) {
  return rules
    .map(
      ({ selector, declarations }) =>
        `  ${selector} {\n${declarations
          .map(({ property, value }) => `    ${property}: ${value};`)
          .join("\n")}\n  }`,
    )
    .join("\n\n");
}

function renderTokens(registry) {
  return `/* Generated from tokens/design-system.tokens.json. Do not edit this file directly. */\n\n@layer base {\n${renderRules(registry.tokens)}\n}\n`;
}

function renderThemes(registry) {
  return `/* Generated from tokens/design-system.tokens.json. Do not edit this file directly. */\n\n${renderRules(registry.themes)}\n`;
}

const COLOR_TOKEN_PREFIXES = [
  "primary-", "secondary-", "tertiary-", "danger-", "warning-", "success-",
  "grayscale-", "overlay", "bg-", "text-", "content-", "action-",
  "selection-", "notice-", "surface-", "footer-", "feedback-", "border-", "status-",
  "focus-ring", "icon-", "field-", "switch-", "radio-", "checkbox-",
  "loading-circular-", "chart-", "white",
];

function renderTailwindColors(registry) {
  const names = new Set();
  for (const rule of registry.tokens) {
    for (const declaration of rule.declarations) {
      if (
        declaration.property.startsWith("--") &&
        COLOR_TOKEN_PREFIXES.some((prefix) => declaration.property.slice(2).startsWith(prefix))
      ) {
        names.add(declaration.property.slice(2));
      }
    }
  }
  const entries = [...names].sort().map(
    (name) => `  ${JSON.stringify(name)}: ${JSON.stringify(`rgba(var(--${name}), <alpha-value>)`)}`,
  );
  return `// Generated from tokens/design-system.tokens.json. Do not edit this file directly.\nmodule.exports = {\n${entries.join(",\n")}\n};\n`;
}

function targetRoots() {
  return [
    path.join(packageRoot, "src"),
    path.join(repositoryRoot, "packages", "design-system", "src"),
  ].filter((root) => fs.existsSync(root));
}

export function generateTokenFiles({ check = false } = {}) {
  if (!fs.existsSync(registryPath)) {
    throw new Error(`Registro de tokens ausente: ${registryPath}`);
  }
  const registry = JSON.parse(fs.readFileSync(registryPath, "utf8"));
  if (
    registry.version !== 1 ||
    !Array.isArray(registry.tokens) ||
    !Array.isArray(registry.themes)
  ) {
    throw new Error("Registro de tokens invalido: esperado version 1 com tokens e themes.");
  }
  const expected = {
    tokens: renderTokens(registry),
    themes: renderThemes(registry),
  };
  const mismatches = [];

  for (const root of targetRoots()) {
    for (const [name, content] of Object.entries(expected)) {
      const outputPath = path.join(root, `${name}.css`);
      const current = fs.existsSync(outputPath)
        ? fs.readFileSync(outputPath, "utf8")
        : "";
      if (current !== content) {
        mismatches.push(path.relative(repositoryRoot, outputPath));
        if (!check) fs.writeFileSync(outputPath, content);
      }
    }
  }

  const tailwindColorsPath = path.join(packageRoot, "tokens", "tailwind-colors.cjs");
  const tailwindColors = renderTailwindColors(registry);
  const currentTailwindColors = fs.existsSync(tailwindColorsPath)
    ? fs.readFileSync(tailwindColorsPath, "utf8")
    : "";
  if (currentTailwindColors !== tailwindColors) {
    mismatches.push(path.relative(repositoryRoot, tailwindColorsPath));
    if (!check) fs.writeFileSync(tailwindColorsPath, tailwindColors);
  }

  if (check && mismatches.length > 0) {
    throw new Error(
      `Arquivos de tokens fora de sincronia com o registro: ${mismatches.join(", ")}`,
    );
  }

  return {
    files: [
      path.relative(repositoryRoot, tailwindColorsPath),
      ...targetRoots().flatMap((root) => [
        path.relative(repositoryRoot, path.join(root, "tokens.css")),
        path.relative(repositoryRoot, path.join(root, "themes.css")),
      ]),
    ],
  };
}

if (process.argv.includes("--init")) {
  fs.mkdirSync(path.dirname(registryPath), { recursive: true });
  fs.writeFileSync(registryPath, `${JSON.stringify(createRegistry(), null, 2)}\n`);
  process.stdout.write(`Registro criado: ${path.relative(repositoryRoot, registryPath)}\n`);
}

if (process.argv.includes("--check")) {
  generateTokenFiles({ check: true });
  process.stdout.write("Tokens do Design System: OK\n");
} else if (process.argv.includes("--init") || process.argv.includes("--write")) {
  const result = generateTokenFiles();
  process.stdout.write(`Tokens gerados: ${result.files.join(", ")}\n`);
}
