import {
  COUNTRY_OPTIONS as COUNTRY_METADATA_OPTIONS,
  filterCountryOptions,
  getCountryOptions as getMetadataCountryOptions,
  type DesignSystemCountryOption,
} from "./data/country-metadata";

export type {
  CountryListFilter,
  CountryListMode,
  DesignSystemCountryOption,
} from "./data/country-metadata";

export { filterCountryOptions };

const countryFlagUrls: Record<string, string> = {
  ad: new URL("./flags/ad.svg", import.meta.url).toString(),
  ae: new URL("./flags/ae.svg", import.meta.url).toString(),
  af: new URL("./flags/af.svg", import.meta.url).toString(),
  ag: new URL("./flags/ag.svg", import.meta.url).toString(),
  ai: new URL("./flags/ai.svg", import.meta.url).toString(),
  al: new URL("./flags/al.svg", import.meta.url).toString(),
  am: new URL("./flags/am.svg", import.meta.url).toString(),
  ao: new URL("./flags/ao.svg", import.meta.url).toString(),
  aq: new URL("./flags/aq.svg", import.meta.url).toString(),
  ar: new URL("./flags/ar.svg", import.meta.url).toString(),
  as: new URL("./flags/as.svg", import.meta.url).toString(),
  at: new URL("./flags/at.svg", import.meta.url).toString(),
  au: new URL("./flags/au.svg", import.meta.url).toString(),
  aw: new URL("./flags/aw.svg", import.meta.url).toString(),
  ax: new URL("./flags/ax.svg", import.meta.url).toString(),
  az: new URL("./flags/az.svg", import.meta.url).toString(),
  ba: new URL("./flags/ba.svg", import.meta.url).toString(),
  bb: new URL("./flags/bb.svg", import.meta.url).toString(),
  bd: new URL("./flags/bd.svg", import.meta.url).toString(),
  be: new URL("./flags/be.svg", import.meta.url).toString(),
  bf: new URL("./flags/bf.svg", import.meta.url).toString(),
  bg: new URL("./flags/bg.svg", import.meta.url).toString(),
  bh: new URL("./flags/bh.svg", import.meta.url).toString(),
  bi: new URL("./flags/bi.svg", import.meta.url).toString(),
  bj: new URL("./flags/bj.svg", import.meta.url).toString(),
  bl: new URL("./flags/bl.svg", import.meta.url).toString(),
  bm: new URL("./flags/bm.svg", import.meta.url).toString(),
  bn: new URL("./flags/bn.svg", import.meta.url).toString(),
  bo: new URL("./flags/bo.svg", import.meta.url).toString(),
  bq: new URL("./flags/bq.svg", import.meta.url).toString(),
  br: new URL("./flags/br.svg", import.meta.url).toString(),
  bs: new URL("./flags/bs.svg", import.meta.url).toString(),
  bt: new URL("./flags/bt.svg", import.meta.url).toString(),
  bv: new URL("./flags/bv.svg", import.meta.url).toString(),
  bw: new URL("./flags/bw.svg", import.meta.url).toString(),
  by: new URL("./flags/by.svg", import.meta.url).toString(),
  bz: new URL("./flags/bz.svg", import.meta.url).toString(),
  ca: new URL("./flags/ca.svg", import.meta.url).toString(),
  cc: new URL("./flags/cc.svg", import.meta.url).toString(),
  cd: new URL("./flags/cd.svg", import.meta.url).toString(),
  cf: new URL("./flags/cf.svg", import.meta.url).toString(),
  cg: new URL("./flags/cg.svg", import.meta.url).toString(),
  ch: new URL("./flags/ch.svg", import.meta.url).toString(),
  ci: new URL("./flags/ci.svg", import.meta.url).toString(),
  ck: new URL("./flags/ck.svg", import.meta.url).toString(),
  cl: new URL("./flags/cl.svg", import.meta.url).toString(),
  cm: new URL("./flags/cm.svg", import.meta.url).toString(),
  cn: new URL("./flags/cn.svg", import.meta.url).toString(),
  co: new URL("./flags/co.svg", import.meta.url).toString(),
  cr: new URL("./flags/cr.svg", import.meta.url).toString(),
  cu: new URL("./flags/cu.svg", import.meta.url).toString(),
  cv: new URL("./flags/cv.svg", import.meta.url).toString(),
  cw: new URL("./flags/cw.svg", import.meta.url).toString(),
  cx: new URL("./flags/cx.svg", import.meta.url).toString(),
  cy: new URL("./flags/cy.svg", import.meta.url).toString(),
  cz: new URL("./flags/cz.svg", import.meta.url).toString(),
  de: new URL("./flags/de.svg", import.meta.url).toString(),
  dj: new URL("./flags/dj.svg", import.meta.url).toString(),
  dk: new URL("./flags/dk.svg", import.meta.url).toString(),
  dm: new URL("./flags/dm.svg", import.meta.url).toString(),
  do: new URL("./flags/do.svg", import.meta.url).toString(),
  dz: new URL("./flags/dz.svg", import.meta.url).toString(),
  ec: new URL("./flags/ec.svg", import.meta.url).toString(),
  ee: new URL("./flags/ee.svg", import.meta.url).toString(),
  eg: new URL("./flags/eg.svg", import.meta.url).toString(),
  eh: new URL("./flags/eh.svg", import.meta.url).toString(),
  er: new URL("./flags/er.svg", import.meta.url).toString(),
  es: new URL("./flags/es.svg", import.meta.url).toString(),
  et: new URL("./flags/et.svg", import.meta.url).toString(),
  fi: new URL("./flags/fi.svg", import.meta.url).toString(),
  fj: new URL("./flags/fj.svg", import.meta.url).toString(),
  fk: new URL("./flags/fk.svg", import.meta.url).toString(),
  fm: new URL("./flags/fm.svg", import.meta.url).toString(),
  fo: new URL("./flags/fo.svg", import.meta.url).toString(),
  fr: new URL("./flags/fr.svg", import.meta.url).toString(),
  ga: new URL("./flags/ga.svg", import.meta.url).toString(),
  gb: new URL("./flags/gb.svg", import.meta.url).toString(),
  gd: new URL("./flags/gd.svg", import.meta.url).toString(),
  ge: new URL("./flags/ge.svg", import.meta.url).toString(),
  gf: new URL("./flags/gf.svg", import.meta.url).toString(),
  gg: new URL("./flags/gg.svg", import.meta.url).toString(),
  gh: new URL("./flags/gh.svg", import.meta.url).toString(),
  gi: new URL("./flags/gi.svg", import.meta.url).toString(),
  gl: new URL("./flags/gl.svg", import.meta.url).toString(),
  gm: new URL("./flags/gm.svg", import.meta.url).toString(),
  gn: new URL("./flags/gn.svg", import.meta.url).toString(),
  gp: new URL("./flags/gp.svg", import.meta.url).toString(),
  gq: new URL("./flags/gq.svg", import.meta.url).toString(),
  gr: new URL("./flags/gr.svg", import.meta.url).toString(),
  gs: new URL("./flags/gs.svg", import.meta.url).toString(),
  gt: new URL("./flags/gt.svg", import.meta.url).toString(),
  gu: new URL("./flags/gu.svg", import.meta.url).toString(),
  gw: new URL("./flags/gw.svg", import.meta.url).toString(),
  gy: new URL("./flags/gy.svg", import.meta.url).toString(),
  hk: new URL("./flags/hk.svg", import.meta.url).toString(),
  hm: new URL("./flags/hm.svg", import.meta.url).toString(),
  hn: new URL("./flags/hn.svg", import.meta.url).toString(),
  hr: new URL("./flags/hr.svg", import.meta.url).toString(),
  ht: new URL("./flags/ht.svg", import.meta.url).toString(),
  hu: new URL("./flags/hu.svg", import.meta.url).toString(),
  id: new URL("./flags/id.svg", import.meta.url).toString(),
  ie: new URL("./flags/ie.svg", import.meta.url).toString(),
  il: new URL("./flags/il.svg", import.meta.url).toString(),
  im: new URL("./flags/im.svg", import.meta.url).toString(),
  in: new URL("./flags/in.svg", import.meta.url).toString(),
  io: new URL("./flags/io.svg", import.meta.url).toString(),
  iq: new URL("./flags/iq.svg", import.meta.url).toString(),
  ir: new URL("./flags/ir.svg", import.meta.url).toString(),
  is: new URL("./flags/is.svg", import.meta.url).toString(),
  it: new URL("./flags/it.svg", import.meta.url).toString(),
  je: new URL("./flags/je.svg", import.meta.url).toString(),
  jm: new URL("./flags/jm.svg", import.meta.url).toString(),
  jo: new URL("./flags/jo.svg", import.meta.url).toString(),
  jp: new URL("./flags/jp.svg", import.meta.url).toString(),
  ke: new URL("./flags/ke.svg", import.meta.url).toString(),
  kg: new URL("./flags/kg.svg", import.meta.url).toString(),
  kh: new URL("./flags/kh.svg", import.meta.url).toString(),
  ki: new URL("./flags/ki.svg", import.meta.url).toString(),
  km: new URL("./flags/km.svg", import.meta.url).toString(),
  kn: new URL("./flags/kn.svg", import.meta.url).toString(),
  kp: new URL("./flags/kp.svg", import.meta.url).toString(),
  kr: new URL("./flags/kr.svg", import.meta.url).toString(),
  kw: new URL("./flags/kw.svg", import.meta.url).toString(),
  ky: new URL("./flags/ky.svg", import.meta.url).toString(),
  kz: new URL("./flags/kz.svg", import.meta.url).toString(),
  la: new URL("./flags/la.svg", import.meta.url).toString(),
  lb: new URL("./flags/lb.svg", import.meta.url).toString(),
  lc: new URL("./flags/lc.svg", import.meta.url).toString(),
  li: new URL("./flags/li.svg", import.meta.url).toString(),
  lk: new URL("./flags/lk.svg", import.meta.url).toString(),
  lr: new URL("./flags/lr.svg", import.meta.url).toString(),
  ls: new URL("./flags/ls.svg", import.meta.url).toString(),
  lt: new URL("./flags/lt.svg", import.meta.url).toString(),
  lu: new URL("./flags/lu.svg", import.meta.url).toString(),
  lv: new URL("./flags/lv.svg", import.meta.url).toString(),
  ly: new URL("./flags/ly.svg", import.meta.url).toString(),
  ma: new URL("./flags/ma.svg", import.meta.url).toString(),
  mc: new URL("./flags/mc.svg", import.meta.url).toString(),
  md: new URL("./flags/md.svg", import.meta.url).toString(),
  me: new URL("./flags/me.svg", import.meta.url).toString(),
  mf: new URL("./flags/mf.svg", import.meta.url).toString(),
  mg: new URL("./flags/mg.svg", import.meta.url).toString(),
  mh: new URL("./flags/mh.svg", import.meta.url).toString(),
  mk: new URL("./flags/mk.svg", import.meta.url).toString(),
  ml: new URL("./flags/ml.svg", import.meta.url).toString(),
  mm: new URL("./flags/mm.svg", import.meta.url).toString(),
  mn: new URL("./flags/mn.svg", import.meta.url).toString(),
  mo: new URL("./flags/mo.svg", import.meta.url).toString(),
  mp: new URL("./flags/mp.svg", import.meta.url).toString(),
  mq: new URL("./flags/mq.svg", import.meta.url).toString(),
  mr: new URL("./flags/mr.svg", import.meta.url).toString(),
  ms: new URL("./flags/ms.svg", import.meta.url).toString(),
  mt: new URL("./flags/mt.svg", import.meta.url).toString(),
  mu: new URL("./flags/mu.svg", import.meta.url).toString(),
  mv: new URL("./flags/mv.svg", import.meta.url).toString(),
  mw: new URL("./flags/mw.svg", import.meta.url).toString(),
  mx: new URL("./flags/mx.svg", import.meta.url).toString(),
  my: new URL("./flags/my.svg", import.meta.url).toString(),
  mz: new URL("./flags/mz.svg", import.meta.url).toString(),
  na: new URL("./flags/na.svg", import.meta.url).toString(),
  nc: new URL("./flags/nc.svg", import.meta.url).toString(),
  ne: new URL("./flags/ne.svg", import.meta.url).toString(),
  nf: new URL("./flags/nf.svg", import.meta.url).toString(),
  ng: new URL("./flags/ng.svg", import.meta.url).toString(),
  ni: new URL("./flags/ni.svg", import.meta.url).toString(),
  nl: new URL("./flags/nl.svg", import.meta.url).toString(),
  no: new URL("./flags/no.svg", import.meta.url).toString(),
  np: new URL("./flags/np.svg", import.meta.url).toString(),
  nr: new URL("./flags/nr.svg", import.meta.url).toString(),
  nu: new URL("./flags/nu.svg", import.meta.url).toString(),
  nz: new URL("./flags/nz.svg", import.meta.url).toString(),
  om: new URL("./flags/om.svg", import.meta.url).toString(),
  pa: new URL("./flags/pa.svg", import.meta.url).toString(),
  pe: new URL("./flags/pe.svg", import.meta.url).toString(),
  pf: new URL("./flags/pf.svg", import.meta.url).toString(),
  pg: new URL("./flags/pg.svg", import.meta.url).toString(),
  ph: new URL("./flags/ph.svg", import.meta.url).toString(),
  pk: new URL("./flags/pk.svg", import.meta.url).toString(),
  pl: new URL("./flags/pl.svg", import.meta.url).toString(),
  pm: new URL("./flags/pm.svg", import.meta.url).toString(),
  pn: new URL("./flags/pn.svg", import.meta.url).toString(),
  pr: new URL("./flags/pr.svg", import.meta.url).toString(),
  ps: new URL("./flags/ps.svg", import.meta.url).toString(),
  pt: new URL("./flags/pt.svg", import.meta.url).toString(),
  pw: new URL("./flags/pw.svg", import.meta.url).toString(),
  py: new URL("./flags/py.svg", import.meta.url).toString(),
  qa: new URL("./flags/qa.svg", import.meta.url).toString(),
  re: new URL("./flags/re.svg", import.meta.url).toString(),
  ro: new URL("./flags/ro.svg", import.meta.url).toString(),
  rs: new URL("./flags/rs.svg", import.meta.url).toString(),
  ru: new URL("./flags/ru.svg", import.meta.url).toString(),
  rw: new URL("./flags/rw.svg", import.meta.url).toString(),
  sa: new URL("./flags/sa.svg", import.meta.url).toString(),
  sb: new URL("./flags/sb.svg", import.meta.url).toString(),
  sc: new URL("./flags/sc.svg", import.meta.url).toString(),
  sd: new URL("./flags/sd.svg", import.meta.url).toString(),
  se: new URL("./flags/se.svg", import.meta.url).toString(),
  sg: new URL("./flags/sg.svg", import.meta.url).toString(),
  sh: new URL("./flags/sh.svg", import.meta.url).toString(),
  si: new URL("./flags/si.svg", import.meta.url).toString(),
  sj: new URL("./flags/sj.svg", import.meta.url).toString(),
  sk: new URL("./flags/sk.svg", import.meta.url).toString(),
  sl: new URL("./flags/sl.svg", import.meta.url).toString(),
  sm: new URL("./flags/sm.svg", import.meta.url).toString(),
  sn: new URL("./flags/sn.svg", import.meta.url).toString(),
  so: new URL("./flags/so.svg", import.meta.url).toString(),
  sr: new URL("./flags/sr.svg", import.meta.url).toString(),
  ss: new URL("./flags/ss.svg", import.meta.url).toString(),
  st: new URL("./flags/st.svg", import.meta.url).toString(),
  sv: new URL("./flags/sv.svg", import.meta.url).toString(),
  sx: new URL("./flags/sx.svg", import.meta.url).toString(),
  sy: new URL("./flags/sy.svg", import.meta.url).toString(),
  sz: new URL("./flags/sz.svg", import.meta.url).toString(),
  tc: new URL("./flags/tc.svg", import.meta.url).toString(),
  td: new URL("./flags/td.svg", import.meta.url).toString(),
  tf: new URL("./flags/tf.svg", import.meta.url).toString(),
  tg: new URL("./flags/tg.svg", import.meta.url).toString(),
  th: new URL("./flags/th.svg", import.meta.url).toString(),
  tj: new URL("./flags/tj.svg", import.meta.url).toString(),
  tk: new URL("./flags/tk.svg", import.meta.url).toString(),
  tl: new URL("./flags/tl.svg", import.meta.url).toString(),
  tm: new URL("./flags/tm.svg", import.meta.url).toString(),
  tn: new URL("./flags/tn.svg", import.meta.url).toString(),
  to: new URL("./flags/to.svg", import.meta.url).toString(),
  tr: new URL("./flags/tr.svg", import.meta.url).toString(),
  tt: new URL("./flags/tt.svg", import.meta.url).toString(),
  tv: new URL("./flags/tv.svg", import.meta.url).toString(),
  tw: new URL("./flags/tw.svg", import.meta.url).toString(),
  tz: new URL("./flags/tz.svg", import.meta.url).toString(),
  ua: new URL("./flags/ua.svg", import.meta.url).toString(),
  ug: new URL("./flags/ug.svg", import.meta.url).toString(),
  um: new URL("./flags/um.svg", import.meta.url).toString(),
  us: new URL("./flags/us.svg", import.meta.url).toString(),
  uy: new URL("./flags/uy.svg", import.meta.url).toString(),
  uz: new URL("./flags/uz.svg", import.meta.url).toString(),
  va: new URL("./flags/va.svg", import.meta.url).toString(),
  vc: new URL("./flags/vc.svg", import.meta.url).toString(),
  ve: new URL("./flags/ve.svg", import.meta.url).toString(),
  vg: new URL("./flags/vg.svg", import.meta.url).toString(),
  vi: new URL("./flags/vi.svg", import.meta.url).toString(),
  vn: new URL("./flags/vn.svg", import.meta.url).toString(),
  vu: new URL("./flags/vu.svg", import.meta.url).toString(),
  wf: new URL("./flags/wf.svg", import.meta.url).toString(),
  ws: new URL("./flags/ws.svg", import.meta.url).toString(),
  xk: new URL("./flags/xk.svg", import.meta.url).toString(),
  ye: new URL("./flags/ye.svg", import.meta.url).toString(),
  yt: new URL("./flags/yt.svg", import.meta.url).toString(),
  za: new URL("./flags/za.svg", import.meta.url).toString(),
  zm: new URL("./flags/zm.svg", import.meta.url).toString(),
  zw: new URL("./flags/zw.svg", import.meta.url).toString(),
};

const countryFlagFiles = new Set(Object.keys(countryFlagUrls));

function normalizedCode(cca2?: string | null) {
  const code = String(cca2 || "").trim().toLowerCase();
  return /^[a-z]{2}$/.test(code) && countryFlagFiles.has(code) ? code : "";
}

/** Browser-safe synchronous URL for a flag shipped by this package. */
export function getCountryFlagUrl(cca2?: string | null) {
  const code = normalizedCode(cca2);
  return code ? countryFlagUrls[code] || "" : "";
}

function withCountryFlag(option: DesignSystemCountryOption): DesignSystemCountryOption {
  return {
    ...option,
    flags: {
      ...option.flags,
      svg: getCountryFlagUrl(option.cca2),
    },
  };
}

/** Browser entrypoint: light metadata and package-local flag URLs. */
export const COUNTRY_OPTIONS: DesignSystemCountryOption[] = COUNTRY_METADATA_OPTIONS.map(
  withCountryFlag,
);

export const PHONE_COUNTRY_OPTIONS = COUNTRY_OPTIONS;

export function getCountryOptions() {
  return getMetadataCountryOptions().map(withCountryFlag);
}

export default COUNTRY_OPTIONS;
